import assert from 'node:assert/strict';
import * as T from './dist/vendor/three.module.js';
import {createLandscape,animateLandscape,disposeArt,bakeArt,createKeep,createStructure} from './dist/art.js';
import {World} from './dist/world.js';
import {DEFS} from './dist/engine.js';
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name);}
function inspect(root){let meshes=0,triangles=0;root.updateMatrixWorld(true);root.traverse(o=>{if(!o.isMesh)return;meshes++;const p=o.geometry.attributes.position;assert.ok(p?.count>0);assert.ok([...p.array].every(Number.isFinite),'No invalid vertices');assert.ok(o.matrixWorld.elements.every(Number.isFinite));triangles+=(o.geometry.index?.count||p.count)/3*(o.isInstancedMesh?o.count:1);});return {meshes,triangles};}
for(const theme of ['meadow','frost','ruins'])test(theme+' scenery has bounded draw calls and disposes on switching',()=>{
 const world={scene:new T.Scene()},land=createLandscape(world,theme),stats=inspect(land.root);assert.ok(stats.meshes<20,JSON.stringify(stats));assert.ok(stats.triangles<65000,JSON.stringify(stats));assert.ok(land.root.userData.bakedFrom>300);assert.ok(land.detail.children.some(o=>o.isMesh),'Quality detail batch survives parent baking');
 animateLandscape(land,12,1,true,'low');assert.equal(land.detail.visible,false);animateLandscape(land,12,0,false,'high');assert.equal(land.detail.visible,true);assert.equal(land.waterTime.value,0);
 const geometries=new Set(),disposed=new Set();for(const root of [land.root,land.water])root.traverse(o=>{if(o.geometry&&!geometries.has(o.geometry)){geometries.add(o.geometry);o.geometry.addEventListener('dispose',()=>disposed.add(o.geometry));}});disposeArt(land.root);disposeArt(land.water);assert.equal(world.scene.children.length,0);assert.equal(disposed.size,geometries.size);console.log(JSON.stringify({theme,...stats,sourceProps:land.root.userData.bakedFrom}));
});
test('Batching preserves nested transforms and vertex colors',()=>{const group=new T.Group();group.position.set(4,3,2);const inner=new T.Group();inner.position.set(1,2,3);inner.rotation.y=.6;group.add(inner);const mesh=new T.Mesh(new T.BoxGeometry(1,2,3),new T.MeshStandardMaterial({color:0x558866}));mesh.position.x=2;inner.add(mesh);const before=new T.Box3().setFromObject(group);bakeArt(group);const after=new T.Box3().setFromObject(group);assert.ok(before.min.distanceTo(after.min)<1e-5);assert.ok(before.max.distanceTo(after.max)<1e-5);assert.ok(group.children.find(o=>o.isMesh).geometry.attributes.color);disposeArt(group);});
test('All twelve units retain articulated bones and live caster gems',()=>{for(const [key,def]of Object.entries(DEFS)){const model=World.prototype.unitModel.call({}, {...def,key},3),stats=inspect(model),rig=model.userData.rig;assert.ok(stats.meshes<25,key+' '+stats.meshes);assert.equal(rig.weapon.parent,rig.body);assert.equal(rig.shield.parent,rig.body);if(model.userData.gem)assert.ok(model.userData.gem.parent,key+' gem survives baking');World.prototype.animateUnit.call({time:1,motion:true},model,{id:'u1',moving:true,attackAnim:.09,hit:.08},.016);assert.notEqual(rig.weapon.rotation.x,0);assert.notEqual(rig.left.rotation.x,0);assert.ok(inspect(model).meshes>0);disposeArt(model);}});
test('All building levels and branches render finite geometry and preserve animations',()=>{let variants=0;for(const [type,branches]of Object.entries({tower:['','ballista','frost'],relay:['','pulse','shelter'],farm:['','market','granary']}))for(const level of[1,2,3])for(const branch of branches){const m=createStructure({type,level,branch}),stats=inspect(m);assert.ok(stats.meshes<15,type+' '+stats.meshes);if(type==='farm'&&branch!=='market')assert.equal(m.userData.sails.parent,m);if(type==='relay'||branch==='frost')assert.equal(m.userData.spire.parent,m);disposeArt(m);variants++;}console.log('Building variants: '+variants);});
test('Keep geometry stays within its footprint and retains its animated flag',()=>{const keep=createKeep(),bounds=new T.Box3().setFromObject(keep),stats=inspect(keep);assert.ok(stats.meshes<=5);assert.ok(bounds.max.x<=2.8&&bounds.min.x>=-2.8);assert.ok(bounds.max.y>6);assert.equal(keep.userData.flag.parent,keep);disposeArt(keep);});
test('Scene camera returns to battle projection and zoom',()=>{global.innerWidth=1280;global.innerHeight=720;const world={camera:new T.OrthographicCamera(),renderer:{setSize(){}},zoom:1.25,resize:World.prototype.resize};for(const view of['wide','close','side']){World.prototype.setSceneView.call(world,view);assert.ok(world.camera.projectionMatrix.elements.every(Number.isFinite));assert.equal(world.camera.view?.enabled||false,false);}World.prototype.setSceneView.call(world,null);assert.equal(world.camera.zoom,1.25);assert.deepEqual(world.camera.position.toArray(),[26,37,32]);assert.equal(world.camera.view.enabled,true);});
console.log(checks+' art checks passed.');
