import assert from 'node:assert/strict';
import {Game,DEFS,WAVES,SOCKETS} from './dist/engine.js';
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name);}
test('Purchase merge preserves deployed slot and accounts for gold',()=>{const g=new Game(1);g.buy(0);g.buy(1);assert.equal(g.state.gold,28);assert.equal(g.state.units.length,2);assert.equal(g.state.units[0].star,2);assert.deepEqual(g.state.units[0].slot,{x:-6.4,z:0});assert.equal(g.buy(0).ok,false);assert.equal(g.state.gold,28);});
test('Three two-star units cascade into one three-star unit',()=>{const g=new Game(1);g.state.units=[];for(let i=0;i<9;i++)g.state.units.push(g.makeUnit('sentinel',i===0?{x:3.2,z:0}:null));g.merge();assert.equal(g.state.units.length,1);assert.equal(g.state.units[0].star,3);assert.ok(g.state.units[0].slot);g.sell(g.state.units[0].id);assert.equal(g.state.gold,50);});
test('Population, swaps, recall, bench capacity, and distinct traits',()=>{const g=new Game(1);g.buy(2);g.buy(3);const [w,s]=g.state.units.slice(2);assert.equal(g.deploy(w.id,-6.4,3.2).ok,true);assert.equal(g.deploy(s.id,6.4,3.2).ok,false);assert.equal(g.deploy(s.id,-6.4,3.2).ok,true);assert.equal(w.slot,null);assert.equal(g.traits().ranger,2);assert.equal(g.deploy(w.id,0,0).ok,false);assert.equal(g.recall(s.id).ok,true);assert.equal(g.traits().ranger,1);});
test('Invalid input cannot corrupt a position or spend gold',()=>{const g=new Game(1);assert.equal(g.buy(-1).ok,false);assert.equal(g.build(99,'farm').ok,false);assert.equal(g.build(0,'oops').ok,false);assert.equal(g.choosePerk('wealth').ok,false);assert.equal(g.state.gold,32);});
test('Income uses interest cap and farm level; relay chain extends power',()=>{const g=new Game(1);g.state.gold=100;g.build(0,'farm');g.upgrade(0);assert.deepEqual(g.income(),{base:12,interest:5,farm:8});g.state.core.x=-11;g.state.core.z=0;g.build(2,'relay');assert.equal(g.powered({x:-11,z:13}),true);assert.equal(g.powered({x:18,z:13}),false);});
test('Night closes all economic actions and cooldown prevents repeated nova',()=>{const g=new Game(1);g.startNight();const gold=g.state.gold;assert.equal(g.buy(2).ok,false);assert.equal(g.build(0,'farm').ok,false);assert.equal(g.levelUp().ok,false);assert.equal(g.rollShop().ok,false);assert.equal(g.sell('u1').ok,false);assert.equal(g.nova().ok,true);assert.equal(g.nova().ok,false);assert.equal(g.state.gold,gold);});
test('Daytime save round-trips and rejects malformed saves',()=>{const g=new Game(8);g.buy(0);g.buy(1);g.build(0,'tower');const r=Game.restore(g.serialize());assert.deepEqual(r.state,g.state);assert.equal(r.seed,g.seed);assert.equal(Game.restore('invalid'),null);assert.equal(Game.restore('{"version":1,"state":{}}'),null);g.startNight();assert.equal(g.serialize(),null);});
function runNight(g){let steps=0;while(g.state.phase==='night'&&steps<9000){g.update(.1);if(g.state.hero.skill===0)g.nova();g.events=[];steps++;}assert.ok(steps<9000,'Battle must terminate');for(const e of [...g.state.units,...g.state.enemies])assert.ok(Number.isFinite(e.x)&&Number.isFinite(e.hp));return Math.round(steps/10);}
test('First night is survivable with the starter army',()=>{const g=new Game(7);g.startNight();const seconds=runNight(g);assert.equal(g.state.phase,'reward');assert.equal(g.state.kills,14);assert.ok(g.state.castle.hp>0);assert.equal(g.choosePerk(g.state.reward[0]).ok,true);assert.equal(g.state.round,2);assert.equal(g.state.phase,'day');console.log('  Starter night: '+seconds+' seconds, castle '+g.state.castle.hp);});
test('Defeat is terminal and stops simulation',()=>{const g=new Game(1);g.startNight();g.state.castle.hp=.1;g.state.units=[];g.state.hero.hp=0;g.state.hero.respawn=100;g.state.enemies.push({id:'test',kind:'enemy',x:0,z:0,hp:999,maxHp:999,damage:999,speed:1,range:3,cd:0,stun:0});g.update(.1);assert.equal(g.state.phase,'lost');const t=g.state.time;g.update(1);assert.equal(g.state.time,t);});
const spots=[[-6.4,0],[-3.2,3.2],[-6.4,-3.2],[3.2,3.2],[3.2,-3.2],[6.4,0],[0,-6.4],[0,6.4]];
function field(g){for(const u of g.state.units.filter(u=>!u.slot)){if(g.deployed().length>=g.state.level)break;const p=spots.find(([x,z])=>!g.deployed().some(v=>Math.hypot(v.slot.x-x,v.slot.z-z)<.2));if(p)g.deploy(u.id,...p);}}
function campaign(seed){const g=new Game(seed);g.buy(0);g.buy(1);g.buy(2);g.buy(4);g.levelUp();field(g);g.build(3,'farm');const results=[];for(let round=1;round<=6;round++){if(round>1){if(g.state.castle.hp<400)g.repair();if(g.state.level<6&&g.state.gold>g.levelCost()+6)g.levelUp();for(let attempt=0;attempt<6;attempt++){for(let i=0;i<5;i++){const key=g.state.shop[i];if(!key)continue;const have=g.state.units.filter(u=>u.def===key);if(g.state.gold>=DEFS[key].cost+2&&(have.some(u=>u.star===1)||(g.deployed().length<g.state.level&&!have.length))){g.buy(i);field(g);}}if(g.state.gold>9&&g.state.units.some(u=>u.star===1))g.rollShop();else break;}if(g.state.gold>=10&&!g.state.buildings.some(b=>b.socket===1&&b.hp>0))g.build(1,'tower');}g.startNight();const sec=runNight(g);results.push({round,sec,hp:Math.ceil(g.state.castle.hp),phase:g.state.phase,army:g.deployed().map(u=>u.def+u.star).join(',')});if(g.state.phase==='lost'||g.state.phase==='won')break;g.choosePerk(g.state.reward.includes('flame')?'flame':g.state.reward.includes('stone')?'stone':g.state.reward[0]);}return{g,results};}
test('A legal economy and recruitment strategy can complete all six nights',()=>{const {g,results}=campaign(19);console.log(JSON.stringify(results,null,2));assert.equal(g.state.phase,'won');assert.equal(g.state.kills,WAVES.reduce((a,w)=>a+w.count,0));assert.ok(g.state.gold>=0);});
console.log(`${checks} gameplay checks passed.`);
